name = "Ipopt"
uuid = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
repo = "https://github.com/jump-dev/Ipopt.jl.git"
version = "1.0.0"

[deps]
Ipopt_jll = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
Ipopt_jll = "=3.13.2, =3.13.4, =300.1400.400"
MathOptInterface = "0.10.5"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
