name = "Ipopt"
uuid = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
repo = "https://github.com/jump-dev/Ipopt.jl.git"
version = "1.2.1"

[deps]
Ipopt_jll = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"

[compat]
Ipopt_jll = "=300.1400.400, =300.1400.403, =300.1400.1000"
MathOptInterface = "1"
OpenBLAS32_jll = "0.3.10"
SnoopPrecompile = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
